service: lambda-express-mongo


provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGO_URI: mongodb://appuser:strongpassword@13.203.200.140:27017/appdb?authSource=appdb
    RAZORPAY_KEY_ID: rzp_test_RxQL1L95BUAxAN
    RAZORPAY_KEY_SECRET: H0Lr6K3s1737YkLhs4hWVgCK
functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: "*"

