service: lambda-express-mongo


provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGO_URI: mongodb://appuser:strongpassword@13.203.200.140:27017/appdb?authSource=appdb
    RAZORPAY_KEY_ID: ${env:RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${env:RAZORPAY_KEY_SECRET}

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: "*"

